= Kali Live Build

This repository will allow you to build a custom Kali ISO. The main benefit is to use it as a https://docs.kali.org/downloading/kali-linux-live-usb-install[bootable USB drive].

From the Kali Website:

____
Our favorite way, and the fastest method, for getting up and running with Kali Linux is to run it “live” from a USB drive. This method has several advantages:

* It’s non-destructive — it makes no changes to the host system’s hard drive or installed OS, and to go back to normal operations, you simply remove the “Kali Live” USB drive and restart the system.
* It’s portable — you can carry Kali Linux in your pocket and have it running in minutes on an available system
* It’s customizable — you can https://docs.kali.org/?p=52[roll your own custom Kali Linux ISO image] and put it onto a USB drive using the same procedures
* It’s potentially persistent — with a bit of extra effort, you can configure your Kali Linux “live” USB drive to have https://docs.kali.org/?p=4902[persistent storage], so the data you collect is saved across reboots
____

https://docs.kali.org/development/live-build-a-custom-kali-iso[Read this first]

*Upstream:*

* http://git.kali.org/gitweb/?p=live-build-config.git;a=summary[Kali's live-build configuration]
* https://gitlab.com/kalilinux/build-scripts/live-build-config.git

== Setup

Ideally, you should build your custom Kali ISO from *within a pre-existing Kali environment.* Using a https://www.kali.org/downloads/[lightweight] or virtualised (https://www.offensive-security.com/kali-linux-vm-vmware-virtualbox-hyperv-image-download/[VMware/VirtualBox]) image is recommended.

As `root`:

----
apt-get install curl git live-build cdebootstrap
----




== Customisations
=== 0x01 – Overwrite the default Kali package list
``` 
cat > kali-config/variant-default/package-lists/kali.list.chroot << EOF
kali-root-login
kali-defaults
kali-menu
kali-debtags
kali-archive-keyring
debian-installer-launcher
alsa-tools
locales-all
dconf-tools
openssh-server
EOF 
```
=== 0x02 Adding Packages By Deb File MAKE SURE ALL FILE NAMES ARE LOWER CASE
```
mkdir kali-config/common/packages.chroot
mv nessus-*amd64.deb kali-config/common/packages.chroot/
```

=== 0x03 Make a copy of your packages file
cp -r kali-confing/common/packages.chroot /root/
mv /root/packages.chroot /root/pakacges

=== 0x04 Check /etc/apt/sources.list
```
change http to https
```

=== 0x04 Optional change wallpaper
```
mkdir -p kali-config/common/includes.chroot/usr/share/wallpapers/kali/contents/images
wget https://www.kali.org/dojo/bh2015/wp-blue.png
mv wp-blue.png kali-config/common/includes.chroot/usr/share/wallpapers/kali/contents/images
```

=== 0x05 Build
```
./build.sh -v
```
=== 0x06 It Bricked :(

well of course it did silly goose, nothing works right the first time  

Did you google the error instead of reading this part :( that may have been a poor choice 

==== Unable to locake package ...

1. make sure that your packages are spelt correctly, (did you put kali-meny instead of menu)
2. Are the packages upercase
  * Here edit these two files
  * chroot/root/packages/Packages
  * chroot/root/packages.chroot
  * everyplace where you see the uppercase package name that failed, change it to lowercase
3. run lb chroot_install-packages install
4. order of lb commands if needed
```
Main porcelain commands
lb config(1)
  creates configuration for live-build
lb bootstrap(1)
  executes the first build stage, creating (bootstraping) a basic Debian root filesystem
lb chroot(1)
  executes the second build stage, building the live OS filesystem
lb installer(1)
  executes the third build stage, obtaining installer components (optional)
lb binary(1)
  executes the fourth build stage, generating a binary image
lb source(1)
  executes the fifth build stage, generating a source image (optional)
lb clean(1)
  cleans up system build directories


Ancillary Commands
lb(1)
  generic live-build script execution wrapper
lb build(1)
  alias for all build stages
```
  
== 0x07 Writing to Disk
install k3b

insert blank disk

project > add files > images/*.iso > write to disk
== References

* https://docs.kali.org/kali-dojo/02-mastering-live-build
* https://github.com/prateepb/kali-live-build

